#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'gps-loss-zone==0.1.0','console_scripts','gps_loss_simulator'
__requires__ = 'gps-loss-zone==0.1.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('gps-loss-zone==0.1.0', 'console_scripts', 'gps_loss_simulator')()
    )
